"""
Known corporate veteran ERGs — seed data for the ERG directory.
Loaded via scripts/run_erg_scrape.py --seed or API seed endpoint.
"""

KNOWN_ERGS = [
    {
        "company": "Amazon",
        "erg_name": "Warriors at Amazon",
        "industry": "Technology",
        "founded_year": 2011,
        "description": "Comprises veterans, active service members, their families, and Amazon employees who support them. Provides professional networking, community outreach programs, and transition assistance.",
        "offerings": ["mentorship", "networking", "career_development", "community_service", "transition_support"],
        "company_size": "enterprise",
        "careers_url": "https://www.amazon.jobs/en/military",
        "erg_url": "https://www.aboutamazon.com/affinity-groups",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "Microsoft",
        "erg_name": "Microsoft Military Affairs / MSSA",
        "industry": "Technology",
        "description": "Provides free training through the Microsoft Software & Systems Academy (MSSA) for transitioning service members. Military Spouse Technology Academy for spouses.",
        "offerings": ["training_program", "career_development", "spouse_support", "mentorship"],
        "company_size": "enterprise",
        "careers_url": "https://military.microsoft.com",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "Google",
        "erg_name": "VetNet",
        "industry": "Technology",
        "description": "Veteran employee resource group supporting veteran hiring through Grow with Google initiative and Google Career Certificates program. Partners with Hiring Our Heroes.",
        "offerings": ["mentorship", "networking", "training_program", "career_development"],
        "company_size": "enterprise",
        "careers_url": "https://about.google/intl/ALL_us/belonging/veterans/",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "JPMorgan Chase",
        "erg_name": "Military & Veterans Network",
        "industry": "Financial Services",
        "description": "Co-founded the Veteran Jobs Mission coalition. Over 18,000 veteran employees. Offers Military Pathways internship program and dedicated military recruiting team.",
        "offerings": ["mentorship", "networking", "career_development", "hiring_pipeline", "internship"],
        "company_size": "enterprise",
        "careers_url": "https://careers.jpmorgan.com/us/en/military",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "Johnson & Johnson",
        "erg_name": "Veterans Leadership Council (VLC)",
        "industry": "Healthcare / Pharmaceutical",
        "description": "Empowers employees to engage in their community and enhance marketplace activities for veterans, service members, and their families.",
        "offerings": ["mentorship", "networking", "community_service", "career_development"],
        "company_size": "enterprise",
        "careers_url": "https://www.careers.jnj.com/military",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "Caterpillar",
        "erg_name": "Armed Forces Support Network (AFSN)",
        "industry": "Manufacturing",
        "founded_year": 2007,
        "description": "Attracts veterans, assists with transition to corporate life, and supports employees and families when called to active duty.",
        "offerings": ["transition_support", "networking", "community_service", "family_support"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Eaton",
        "erg_name": "Veterans Inclusion ERG (iERG)",
        "industry": "Manufacturing",
        "founded_year": 2014,
        "member_count": 600,
        "description": "Helps veterans connect, share experiences, and transition to civilian employment. Provides mentoring and advises organizational leaders on the value veterans bring.",
        "offerings": ["mentorship", "networking", "transition_support", "career_development"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Bayer",
        "erg_name": "BRAVE BRG",
        "industry": "Healthcare / Pharmaceutical",
        "description": "Provides mentorship, transition assistance, and wellness support including Post-Traumatic Stress topics. Partners with DoD SkillBridge initiative.",
        "offerings": ["mentorship", "transition_support", "wellness", "skillbridge_partner"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "ITW (Illinois Tool Works)",
        "erg_name": "Veterans & Allies Alliance (IVAA)",
        "industry": "Manufacturing",
        "description": "Includes representation from all service branches plus veterans of foreign militaries. Partners with HR to communicate benefits service members bring to the organization.",
        "offerings": ["networking", "career_development", "community_service", "mentorship"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Henkel",
        "erg_name": "Military/Veterans ERG",
        "industry": "Consumer Goods / Manufacturing",
        "description": "Engages, supports and develops camaraderie among veterans, spouses, family members and supporters of veterans. Creates safe space to connect over shared experiences.",
        "offerings": ["networking", "community_service", "family_support"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "ASRC Federal",
        "erg_name": "MilComm (Military Community)",
        "industry": "Government Services / Defense",
        "description": "Highlights veterans' unique perspectives and skills. Offers career development and networking. Shares veteran employee stories through LinkedIn Life Page 'Heroes Have a Home Here'.",
        "offerings": ["career_development", "networking", "mentorship"],
        "company_size": "large",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "Dow",
        "erg_name": "VetNet",
        "industry": "Chemical / Manufacturing",
        "description": "Helps veterans transition into civilian careers across operations, manufacturing, supply chain, IT, HR. Awarded 'Veteran-Friendly Employer' by Michigan Veterans Affairs Agency.",
        "offerings": ["mentorship", "career_development", "networking"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Wells Fargo",
        "erg_name": "Veteran Team Member Network",
        "industry": "Financial Services",
        "description": "Promotes awareness, mentorship, and career development within the veteran community. Offers veteran apprenticeship and internship programs with dedicated Military Talent Liaisons.",
        "offerings": ["mentorship", "career_development", "internship", "hiring_pipeline"],
        "company_size": "enterprise",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "CACI",
        "erg_name": "Veterans ERG",
        "industry": "Defense / Technology",
        "member_count": 200,
        "description": "Nearly 200 veterans serve on committees from media relations to charity service to business development. Active community engagement and recruiting support.",
        "offerings": ["networking", "community_service", "career_development", "recruiting_support"],
        "company_size": "large",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "AT&T",
        "erg_name": "AT&T Veterans",
        "industry": "Telecommunications",
        "member_count": 3500,
        "description": "Independent 501c3 charitable organization comprised of AT&T employees and retirees. Promotes understanding of sacrifices and contributions made by veterans. 3,500+ members.",
        "offerings": ["networking", "community_service", "mentorship", "career_development"],
        "company_size": "enterprise",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "Liberty Mutual",
        "erg_name": "Valor@Liberty+Allies",
        "industry": "Insurance",
        "description": "Partners with Hiring Our Heroes to directly recruit veterans and military spouses. Offers up to two years of pay differential and benefits continuation for active duty.",
        "offerings": ["hiring_pipeline", "spouse_support", "military_leave_benefits"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Dynatrace",
        "erg_name": "Dynaspace for Veterans",
        "industry": "Technology",
        "description": "Creates a safe space for veterans, their families and those interested in the history and lifestyle of armed forces members. Contributes to veteran charities.",
        "offerings": ["networking", "community_service", "family_support"],
        "company_size": "large",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Siemens Energy",
        "erg_name": "Veterans ERG",
        "industry": "Energy / Engineering",
        "description": "Based in Orlando, FL. Assists Siemens and fellow veterans with translating military resumes into corporate resumes. Active LinkedIn presence for veteran hiring.",
        "offerings": ["resume_support", "career_development", "networking"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Allstate",
        "erg_name": "Veterans ERG",
        "industry": "Insurance",
        "description": "Founded by a general, with former military leaders at top management levels. ERG supports veterans and partners with leadership. Formal recruiting and development program for agency staff.",
        "offerings": ["career_development", "mentorship", "hiring_pipeline"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Stanley Black & Decker",
        "erg_name": "Veterans Network ERG",
        "industry": "Manufacturing",
        "description": "Started with 5 passionate individuals and grew organically. Partners with The Manufacturing Institute Heroes MAKE America initiative. Provides resources and community for veteran employees.",
        "offerings": ["networking", "community_service", "career_development"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Xcel Energy",
        "erg_name": "Veterans ERG",
        "industry": "Energy / Utilities",
        "description": "Regulated utility with engineering-focused culture that mirrors military structure. Processes and technical mindset familiar to veterans.",
        "offerings": ["networking", "mentorship", "career_development"],
        "company_size": "large",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "FDM Group",
        "erg_name": "FDM Veterans Program",
        "industry": "Technology / Consulting",
        "description": "Holds regular lunch sessions for veteran employees only as mentorship platform. Partners with US Chamber of Commerce eMentor program through Hiring Our Heroes. Signed ESGR Statement of Support.",
        "offerings": ["mentorship", "networking", "career_development", "training_program"],
        "company_size": "large",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "Lockheed Martin",
        "erg_name": "Military Veteran Network",
        "industry": "Aerospace / Defense",
        "description": "One in five of approximately 114,000 employees have served in uniform. States 'veterans are at the center of everything we do.' Extensive training and transition programs.",
        "offerings": ["career_development", "hiring_pipeline", "mentorship", "transition_support", "training_program"],
        "company_size": "enterprise",
        "military_friendly_rating": "top_employer",
    },
    {
        "company": "House of Blues / Live Nation",
        "erg_name": "Hero Nation",
        "industry": "Entertainment",
        "description": "Veteran Employee Resource Group focused on diversity hiring and supporting veteran team members in the entertainment industry.",
        "offerings": ["networking", "career_development"],
        "company_size": "enterprise",
        "military_friendly_rating": "military_friendly",
    },
    {
        "company": "8-koi",
        "erg_name": "VERGe (Veteran Employee Resource Group)",
        "industry": "Professional Services",
        "founded_year": 2022,
        "description": "Led by COO (20-year USAF retired Lt. Col). Enhances career opportunities, facilitates transition, provides life coaching and mentoring, fosters collaboration between veteran and civilian employees.",
        "offerings": ["mentorship", "career_development", "transition_support", "coaching"],
        "company_size": "small",
        "military_friendly_rating": "military_friendly",
    },
]

OFFERING_TYPES = [
    "mentorship",
    "networking",
    "career_development",
    "transition_support",
    "training_program",
    "hiring_pipeline",
    "internship",
    "community_service",
    "family_support",
    "spouse_support",
    "wellness",
    "resume_support",
    "skillbridge_partner",
    "coaching",
    "recruiting_support",
    "military_leave_benefits",
]
